{
  "formatVersion": "1.1",
  "component": {
    "group": "com.anymao.where",
    "module": "where",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o63qhqta7vbwdbzv2khcdncwii"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "where-1.0.0.jar",
          "url": "where-1.0.0.jar",
          "size": 23542,
          "sha512": "6d81934526a3fec6d55d721ec46721fd6a77adbb3e7264f17bdb85ab4df07b545984ccc0e51bbc81b9f4547bc54526c823550fb5cb76510009fecb1eafa56192",
          "sha256": "1f216022ad1756c8397470b3455b18b8362a21ce4b8df9afd36a30f7c826f3e2",
          "sha1": "1d456febfc5b60c473cdb1e35f15009eff91503e",
          "md5": "028493c468d93d3a0927eed844928c02"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        }
      ],
      "files": [
        {
          "name": "where-1.0.0.jar",
          "url": "where-1.0.0.jar",
          "size": 23542,
          "sha512": "6d81934526a3fec6d55d721ec46721fd6a77adbb3e7264f17bdb85ab4df07b545984ccc0e51bbc81b9f4547bc54526c823550fb5cb76510009fecb1eafa56192",
          "sha256": "1f216022ad1756c8397470b3455b18b8362a21ce4b8df9afd36a30f7c826f3e2",
          "sha1": "1d456febfc5b60c473cdb1e35f15009eff91503e",
          "md5": "028493c468d93d3a0927eed844928c02"
        }
      ]
    }
  ]
}
